//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 14.05.2016 21:41:32 by NFX.Templatization.TextCSTemplateCompiler at Y470

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using Wave.UrlShortener.Models; 
using NFX; 
using NFX.Wave; 
using NFX.Wave.Templatization; 

namespace Wave.UrlShortener.Pages 
{

 ///<summary>
 /// Auto-generated from template
 ///</summary>
 public  class Index : Wave.UrlShortener.Pages.Master
 {


  public IEnumerable<UrlRecord> Urls { get; set; }


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Index._66_S_LITERAL_0 );

     }
    protected override void  renderBody()
    {
        Target.Write( Index._66_S_LITERAL_1 );
      foreach (var url in Urls){
        Target.Write( Index._66_S_LITERAL_2 );
        Target.Write(Target.Encode( url.ID ));
        Target.Write( Index._66_S_LITERAL_3 );
        Target.Write(Target.Encode( url.OriginalUrl ));
        Target.Write( Index._66_S_LITERAL_4 );
      RemoveScheme(url.OriginalUrl);
        Target.Write( Index._66_S_LITERAL_5 );
        Target.Write(Target.Encode( url.CreateDate ));
        Target.Write( Index._66_S_LITERAL_6 );
        Target.Write(Target.Encode( url.ShortUrl ));
        Target.Write( Index._66_S_LITERAL_4 );
      RemoveScheme(url.ShortUrl);
        Target.Write( Index._66_S_LITERAL_7 );
        Target.Write(Target.Encode( url.ID ));
        Target.Write( Index._66_S_LITERAL_8 );
      }
        Target.Write( Index._66_S_LITERAL_9 );

    }
    protected void RemoveScheme(string url)
    {
        Target.Write( Index._66_S_LITERAL_0 );
       var uri =new Uri(url);
        Target.Write( Index._66_S_LITERAL_0 );
        Target.Write(Target.Encode( uri.Host + uri.PathAndQuery ));

    }


     #region Literal blocks content
        private const string _66_S_LITERAL_0 = @"
"; 
        private const string _66_S_LITERAL_1 = @"
<div>
    <h1>Url shortener</h1>
    <form class=""block"" action=""/Home/AddUrl"" method=""POST"">
        <label>
            Paste your long URL here:
            <input name=""url""/>
        </label>
        <button type=""submit"">Shorten URL</button>
    </form>
    <table class=""url-table"">
        <thead>
            <tr>
                <th>Long Url</th>
                <th>Created</th>
                <th>Short Url</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            "; 
        private const string _66_S_LITERAL_2 = @"
            <tr id="""; 
        private const string _66_S_LITERAL_3 = @""">
                <td><a href="""; 
        private const string _66_S_LITERAL_4 = @""">"; 
        private const string _66_S_LITERAL_5 = @"</a></td>
                <td>"; 
        private const string _66_S_LITERAL_6 = @"</td>
                <td><a href="""; 
        private const string _66_S_LITERAL_7 = @"</a></td>
                <td><a href=""#"" class=""btn remove"" data-id="""; 
        private const string _66_S_LITERAL_8 = @""">Remove</a></td>
            </tr>
            "; 
        private const string _66_S_LITERAL_9 = @"
        </tbody>
    </table>
</div>

<script type=""text/javascript"">
    (function() {
        function remove(event) {
            var id = this.getAttribute('data-id');
            var request = new XMLHttpRequest();
            request.open(""POST"", '/Home/Remove?id=' + id);
            request.onreadystatechange = function() {
                if (request.readyState == 4 && request.status == 200) {
                    var row = WAVE.id(id);
                    row.remove();
                }
            }
            request.send();
            event.preventDefault();
        }

        var removeBtns = document.getElementsByClassName(""btn remove"");
        for (var i = 0; i < removeBtns.length; i++) {
            removeBtns[i].addEventListener('click', remove);
        }
    })();

</script>

"; 
     #endregion

 }//class
}//namespace
