//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 14.05.2016 21:41:32 by NFX.Templatization.TextCSTemplateCompiler at Y470

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using NFX; 
using NFX.Wave; 
using NFX.Wave.Templatization; 

namespace Wave.UrlShortener.Pages 
{

 ///<summary>
 /// Auto-generated from template
 ///</summary>
 public abstract class Master : NFX.Wave.Templatization.WaveTemplate
 {


  protected abstract void renderBody();
  protected virtual void renderStyles() { }


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Master._76_S_LITERAL_0 );
        Target.Write( Master._76_S_LITERAL_1 );
      renderStyles();
        Target.Write( Master._76_S_LITERAL_2 );
      renderBody();
        Target.Write( Master._76_S_LITERAL_3 );

     }


     #region Literal blocks content
        private const string _76_S_LITERAL_0 = @"

"; 
        private const string _76_S_LITERAL_1 = @"
<!DOCTYPE html>
<html>
<head>
  "; 
        private const string _76_S_LITERAL_2 = @"
  <link rel=""stylesheet"" href=""/res/site.css"" type=""text/css"">
  <script src=""/stock/site/script/wv.js""></script>
  <script src=""/stock/site/script/wv.gui.js""></script>
</head>
<body> 
  <div id=""root"">
    "; 
        private const string _76_S_LITERAL_3 = @"
  </div>
</body>
</html>"; 
     #endregion

 }//class
}//namespace
